### ISSUE TITLE
Dashboard devices not showing on Z-Way 2.3.7.

### ISSUE THREAD

**Issue by fermit** [ardevd/habitat#1]
Dashboard content is not loaded to "Home" page with z-way version 2.3.7

**Comment by ardevd** [comment]
@fermit Thank you for taking the time to post the error. Could you share some details on what exactly happens when you try to load the dashboard? Does the weather data show up (if configured)? Do you get any error messages? 

Cheers!

**Comment by ardevd** [comment]
@fermit I'm installing 2.3.7 now. Will report back once Ive tested it. From the changelog I cant see anything that sticks out but I'll keep you posted.

**Comment by ardevd** [comment]
Bug confirmed. Seems the ZWay profile API has changed in 2.3.7 and the way the app parses the correct user data is no longer working. Need to come up with a new solution.

@fermit Thank you for reporting this. I will implement a fix ASAP.

**Comment by ardevd** [comment]
This is now fixed. Will push out new app update on Google Play asap.
