### ISSUE TITLE
Disable admin-only features for non-admin users

### ISSUE THREAD

**Issue by mjsambol** [ardevd/habitat#10]
Following our previous thread, re. non-admin user's ability to restart the controller: my point was that a non admin should *not* be able to restart the controller, but when logged in to the app as non-admin I do have that option.

In all other respects non-admin functionality seems to be working as it should be.

Thanks again for the collaboration, I'm glad to have this option and will pass along any other feedback that comes up!

**Comment by ardevd** [comment]
Have you tried actually restarting the controller? Does it work as a non-admin user?

**Comment by mjsambol** [comment]
Nope, it doesn't work: Controller restart failed, Authentication error.

Which is good. I suggest that better would be not showing the option at all (and same for the Modules screen), but that's a low priority improvement.

A few other observations:

* Device event notifications: the label reads 
Z-Wave device event
undefined : undefined
though the event log shows correct names and labels.

* On the Rooms screen, the # of devices in each room is incorrect, though when I click through to the room the number of devices shown is correct, as is the label at the top. E.g. on the Rooms screen it shows globalRoom 13 devices, but after I click that it shows globalRoom - Devices (8). 

Other than that, so far so good, thanks for the app! I'm going to send some more traffic your way:
http://forum.z-wave.me/viewtopic.php?f=3419&t=29958

**Comment by ardevd** [comment]
Thanks for that. I'll look into why the device count for rooms in the rooms list is incorrect and see if I can find an elegant way to detect whether a logged in user is admin (should be simple) and disable admin-only functionality. 

Cheers for the forum reference!

**Comment by ardevd** [comment]
I've currently made it so that you get a nice message telling you controller restarting is not permitted for non-admin users. I guess perhaps I should just hide the button completely for non-admin users but I havent found a visually pleasing solution to it yet. Marking this as closed for now.

Thanks for the feedback!
