### ISSUE TITLE
Mysterious notifications and log messages

### ISSUE THREAD

**Issue by mjsambol** [ardevd/habitat#11]
A few days ago I started receiving several notifications a day, at unexpected times when nothing was going on with my devices. The notifications are all

Z-Wave device event undefined : undefined

so I don't know where they're coming from or what they mean. I don't see anything going on at that time in the Events window.

Looking in the Habitat application logs I see a LONG list of messages like:

timestamp
Value Z-Wave device ID is back to life: 3 at message of type java.lang.String cannot be converted to JSONObject

timestamp
Value Connection lost to Z-Wave device ID: 3 at  message of type java.lang.String cannot be converted to JSONObject

these two are repeated many times - at least hundreds, if not thousands. If there's a scrollbar it's too small to even see.

Can you please improve the error messages and / or suggest how I can determine what's causing this recent storm?

**Comment by ardevd** [comment]
Hi there.

These notifications come from the Habitat Support Z-way module. Please log into your Zway smarthome UI and verify how you've configured the Habitat module app there. The logs seem to indicate that there is a parsing bug in the Android app as well but they dont explain the notifications you receive.

**Comment by mjsambol** [comment]
The only thing configured server side is what type of events to send at the level of error / warning / all, and I have only error selected. So I get that something is going wrong server side and this is being reported via the app. Unfortunately I have no idea what went wrong, so improving the messages in the app would be very helpful.

**Comment by ardevd** [comment]
Appreciate the feedback. Unfortunately, if the notification pushed from Z-way does not contain any data which seems to be the case here, there's not much the Habitat app can do. But I will look into the issue and see if I can make any improvements. Perhaps the app should just discard notifications without a message?

**Comment by ardevd** [comment]
The upcoming update will no longer show notifications without a title and text. Closing this issue for now.
