### ISSUE TITLE
Scenes are not supported (toggleButton devices)

### ISSUE THREAD

**Issue by blakejrobinson** [ardevd/habitat#3]
I have some scenes set up via the built-in 'Scene' app on my Z-Wave.Me server (for example, 'Heading to bed', 'Leaving the house', etc.). However, when trying to trigger them from the UI nothing seems to happen and 'Device type is not yet supported' appears at the bottom of the screen. No control seems to be shown under the 'Controls' section of the UI.

**Comment by ardevd** [comment]
Thanks for reporting the issue. I have never really worked with Scene's so I havent implemented support for them. I'll look into it asap and see what I can do.

**Comment by blakejrobinson** [comment]
Awesome! Great work on the rest of the app - It really has made z-wave.me usable on my phone.

**Comment by ardevd** [comment]
Thanks for the kind words! I'll keep making it better ;)

**Comment by ardevd** [comment]
@blakejrobinson Support for TOGGLE_BUTTON devices (which includes Scenes) has now been implemented. Version 1.0.7 has been pushed to Google Play.

**Comment by blakejrobinson** [comment]
Awesome, looks like it's working! Many thanks for adding this.

**Comment by ardevd** [comment]
No problem, bud! Let me know if you need anything else :)
